name: 'Colorscheme Request'
description: 'Request to add a colorscheme into the database.'

title: 'Colorscheme request: <Example: folke/tokyonight.nvim>'
labels: ['Type: Colorscheme Request']

body:
  - type: 'textarea'
    attributes:
      label: 'Colorscheme Description'
      description: 'Descript the colorscheme and provide a link to the repository.'
    validations:
      required: true
