name: 'Feature Request'
description: 'Suggest a feature.'

labels: ['Type: Feature Request']

body:
  - type: 'textarea'
    attributes:
      label: 'Feature Description'
      description: 'Descript the feature and why you think it should be added.'
    validations:
      required: true
