name: 'Performance Report'
description: 'Report a performance issue.'

labels: ['Type: Performance']

body:
  - type: 'textarea'
    attributes:
      label: 'Performance Issue Description'
      description: 'Describe the performance issue.'
    validations:
      required: true
  - type: 'dropdown'
    attributes:
      label: 'Operating System'
      options: ['Windows', 'MacOS', 'Linux', 'Other']
    validations:
      required: true
