name: 'Update'

on:
  workflow_dispatch:

jobs:
  update:
    name: 'Update The Database'
    runs-on: 'ubuntu-latest'

    steps: 
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Install Neovim'
        run: 'wget -P ~/ https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz && tar -xf ~/nvim-linux64.tar.gz -C ~/'
      - name: 'Setup Neovim'
        run: 'mv ~/nvim-linux64/bin/nvim /usr/local/bin/nvim && mv ~/nvim-linux64/lib /usr/local/lib/nvim && nvim -v'
      - name: 'Install Zig'
        run: 'wget -P ~/ https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz && tar -xf ~/zig-linux-x86_64-0.13.0.tar.xz -C ~/'
      - name: 'Install Node.js'
        run: 'sudo apt update && sudo apt install nodejs -y && node -v'
      - name: 'Setup Node.js'
        run: 'cd ./database/worker/ npm i'
      - name: 'Run The Worker'
        run: 'npm run start'
